// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBank.Data;

namespace WebBank.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20210528153539_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBank.Models.Currency", b =>
                {
                    b.Property<int>("CurId")
                        .HasColumnName("CurID")
                        .HasColumnType("INT");

                    b.Property<double>("ExchangeRate")
                        .HasColumnType("FLOAT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (255)");

                    b.HasKey("CurId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("WebBank.Models.Deposit", b =>
                {
                    b.Property<int>("DepId")
                        .HasColumnName("DepID")
                        .HasColumnType("INT");

                    b.Property<string>("AddCond")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (255)");

                    b.Property<int>("CurId")
                        .HasColumnName("CurID")
                        .HasColumnType("INT");

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<double>("InterestRate")
                        .HasColumnType("FLOAT");

                    b.Property<int>("MinDepAmount")
                        .HasColumnType("INT");

                    b.Property<string>("MinDepTern")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (255)");

                    b.HasKey("DepId");

                    b.HasIndex("CurId");

                    b.ToTable("Deposit");
                });

            modelBuilder.Entity("WebBank.Models.Depositor", b =>
                {
                    b.Property<int>("DepostorId")
                        .HasColumnName("DepostorID")
                        .HasColumnType("INT");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("VARCHAR (100)");

                    b.Property<int>("DepId")
                        .HasColumnName("DepID")
                        .HasColumnType("INT");

                    b.Property<string>("DepRafMark")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (255)");

                    b.Property<DateTime>("DeposDate")
                        .HasColumnType("DATE");

                    b.Property<int>("EmId")
                        .HasColumnName("EmID")
                        .HasColumnType("INT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR (60)");

                    b.Property<string>("PassData")
                        .IsRequired()
                        .HasColumnType("VARCHAR (20)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("VARCHAR (11)");

                    b.Property<DateTime>("RefundDate")
                        .HasColumnType("DATE");

                    b.Property<int>("SummAm")
                        .HasColumnType("INT");

                    b.Property<int>("SummRef")
                        .HasColumnType("INT");

                    b.HasKey("DepostorId");

                    b.HasIndex("EmId");

                    b.ToTable("Depositor");
                });

            modelBuilder.Entity("WebBank.Models.Employee", b =>
                {
                    b.Property<int>("EmId")
                        .HasColumnName("EmID")
                        .HasColumnType("INT");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (100)");

                    b.Property<int>("Age")
                        .HasColumnType("INT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("Full_Name")
                        .HasColumnType("NVARCHAR (60)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (1)");

                    b.Property<int>("PosId")
                        .HasColumnName("PosID")
                        .HasColumnType("INT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (11)");

                    b.HasKey("EmId");

                    b.HasIndex("PosId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WebBank.Models.Position", b =>
                {
                    b.Property<int>("PosId")
                        .HasColumnName("PosID")
                        .HasColumnType("INT");

                    b.Property<string>("PosName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (60)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (200)");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (200)");

                    b.Property<int>("Salary")
                        .HasColumnType("INT");

                    b.HasKey("PosId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("WebBank.Models.Deposit", b =>
                {
                    b.HasOne("WebBank.Models.Currency", "Cur")
                        .WithMany("Deposit")
                        .HasForeignKey("CurId")
                        .IsRequired();
                });

            modelBuilder.Entity("WebBank.Models.Depositor", b =>
                {
                    b.HasOne("WebBank.Models.Employee", "Em")
                        .WithMany("Depositor")
                        .HasForeignKey("EmId")
                        .IsRequired();
                });

            modelBuilder.Entity("WebBank.Models.Employee", b =>
                {
                    b.HasOne("WebBank.Models.Position", "Pos")
                        .WithMany("Employee")
                        .HasForeignKey("PosId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
